language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: B3AHPyQOX29l3Pegfq4T6t+8plg8s/GSWY9WGzl+iAw+G42XVIfzjDuu6khzYQKiPyRpzpPygqQrHhs1GSImtUmc70n7mfeQXIDlnEZUKpr2hSsEoFzzWaw202PUOFZ6RW9mitWTScrMUUlPkWmf+QLVToDuH7TdvQdYkL37Alh11hmvWIlTJs7sS7nJDD9MVxEKHZ/wXm0JPz3n0n+4dAnFQ9TZSJVdU8dnckJ17Itenief/4yAbehiDqvhH76WLm8xJPmX+uUWCahxqu08Um4hlFzNho7otL0Vrv4I2uOTkxcvYNbZ3Dn8iJXUNDivcwvbVng1a/3lXvWgTe+x72CBBlS5V1q+3nJ5pBk+4IH2ZE6J6ppfvyypGMdkMxxOUOfbT8bYa0HI5BYFYwydebbzcftg3ygMErsvTf5aI4snLuqsJqCciPyavrUD1U2MuQGrIaratXTRe5neQ3ozwjXDJCBqJ3e5I8IYLd1sHivVQBkHEoNHKi4b3Fi3K7zR00q8mfXaszvW9gqxfiSEk3DM5xG61YRQ12zz/P2HibmWK0WZHv3dX3kitVYJv2JTKda7QXCEMfkkpksfPwmYmuqgn1x6NDZCNmQ9mA8UNi/wRTdGSDhSNWsASbB5a5JzOkx1ba+gy7wtuxWYJ7vzM3toH5DiXnqoL5rr4BUuPdk=
  app: nameless-fjord-43314
  on:
    repo: kenttoku/food-tracker-client
